const iBackIcons = "assets/svg/back_arrow.svg";
const iProfile = "assets/svg/profile.svg";
const iArrowUp = "assets/svg/arrow_up.svg";
const iLoading = "assets/svg/Loading.svg";
const iArrowRight = "assets/svg/arrow_right.svg";
const iPhone = "assets/svg/phone.svg";
const iCar = "assets/svg/car_icon.svg";
const iLocation = "assets/svg/location.svg";
const iTick = "assets/images/image 167.png";
